[project]
name = "coffee-shop"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "mysql-connector-python==8.2.0",
    "pyqt6==6.6.1",
    "pyqt6-qt6==6.6.1",
    "pyqt6-sip==13.6.0",
]
